# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(default='', max_length=144, verbose_name='问题')),
                ('a', models.IntegerField(verbose_name='答案|1234')),
                ('x1', models.CharField(default='', max_length=144, verbose_name='选项1')),
                ('x2', models.CharField(default='', max_length=144, verbose_name='选项2')),
                ('x3', models.CharField(default='', max_length=144, verbose_name='选项3')),
                ('x4', models.CharField(default='', max_length=144, verbose_name='选项5')),
            ],
            options={
                'verbose_name': '问题和答案',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=155, verbose_name='问题标签类别')),
            ],
        ),
        migrations.AddField(
            model_name='qa',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ks.Tag', verbose_name='类别'),
        ),
    ]
