# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
