# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170627_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='coruseconnectionstudent',
            name='course_schedule',
            field=models.IntegerField(default=0, verbose_name='课程进度'),
        ),
    ]
