# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(default='', verbose_name='消息')),
            ],
            options={
                'verbose_name': '普通消息推送',
            },
        ),
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('msg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='msg.Msg')),
                ('dt', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '私聊消息',
            },
            bases=('msg.msg',),
        ),
        migrations.AddField(
            model_name='msg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.CreateModel(
            name='MailMsg',
            fields=[
                ('chatmsg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='msg.ChatMsg')),
            ],
            options={
                'verbose_name': '邮箱消息',
            },
            bases=('msg.chatmsg',),
        ),
        migrations.AddField(
            model_name='chatmsg',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
    ]
